### Common properties
spring:
  application:
    name: Home Finder
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    name: home_finder
    username: bsmx
    password: bsmx@2016
    url: jdbc:postgresql://localhost:5432/home_finder
    hikari:
      maximum-pool-size: 10
      idle-timeout: 300000
      minimum-idle: 3
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    show_sql: false
logging:
  level:
    org.springframework: INFO
server:
  port: 9093
