version: '3.7'
services:
  home-finder-postgres:
    container_name: home-finder-postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: home_finder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
